### ISSUE TITLE
1.	Dummy variables 

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#1]
split the data into harness/tape

**Comment by aptperson** [comment]
I don't think this is a dummy variable, you want the data split, into two groups

**Comment by MoniqueLadds** [comment]
thats right, but you have run this correct? and there is not much difference? in that case it would be better to keep the data together

**Comment by aptperson** [comment]
Not much difference, but this was on the discrete variables and we did not have the behaviors sorted when I ran this.
I say we keep the data combined and then see later on

**Comment by aptperson** [comment]
Please confirm what we are doing.

**Comment by MoniqueLadds** [comment]
Keep data combined, ignore harness

**Comment by aptperson** [comment]
Thanks.
