### ISSUE TITLE
Dummy variable of land/water/surface

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#3]
I think this is the highest priority. We have spent a lot of time chasing our tales and running models when we don't have the data sorted. Lets get this sorted first.
It looks like you have tried to do this in "Feature_processing_please_fix" but your code is not very explicit. Further, it looks like you have tried to add back in a dummy that already exists in the data and we have a lookup table for else where (I'm referring to what you have called Behaviour)

**Comment by aptperson** [comment]
Further, I believe that this is already in the raw data? so no merge operation should be required?

**Comment by MoniqueLadds** [comment]
The behaviours is for something else that I want to look at, it is the raw behaviour recorded. It will not be a part of the model.

I'm not sure about the other dummy "land/surface/underwater". I think I have added it in correctly? The "Feature_processing_please_fix" works I think.

**Comment by aptperson** [comment]
I didn't get as far as seeing if it worked, it was going about it in a very weird way so I sought clarity on what it was doing.
It is essentially doing the same thing as assigning the behavior, but with a different list, so it would be better to replicate the methodology used for assigning the behavior to keep the code more readable and consistent.
Also, I spent quite a bit of time making sure the behaviors were being assigned to the correct data.

**Comment by aptperson** [comment]
Also, make sure that you are happy that this is the final data before running any ML. Otherwise you are just wasting computation time on results you are going to throw out.

**Comment by MoniqueLadds** [comment]
OK. I have fixed it about a million times so I feel like it is good now. If you look at the google drive you will see the complete data.

**Comment by MoniqueLadds** [comment]
One small problem...we need to downsample much further than before...

feeding   1595
foraging   249
grooming  245
high_freq     39
 other    1338
resting    876
 thrash   303
travelling      2844

**Comment by aptperson** [comment]
So you fixed the spelling mistakes in the lookup table?

Can you clear out the incorrect behavior code files from the google drive please?

Last time I looked there were still files with the spelling mistakes present, just create an archive file and dump all the old versions there.

This makes me hesitant as I'm not always sure if I'm looking at the correct file.

**Comment by MoniqueLadds** [comment]
Yep, had already given it a bit of a clean up

**Comment by aptperson** [comment]
I have added the Location variable which has two levels. Remember, we need to be able to detect this dummy from the accelerometer signature. Is it possible to detect this. Currently this seems like an observational variable, not a derived one. Please confirm.

**Comment by MoniqueLadds** [comment]
You can't detect from the acc (x,y,z) only from depth. This is the variable you need to use to split on

**Comment by aptperson** [comment]
So the Land/Water/Surface variable has been derived from depth?

**Comment by MoniqueLadds** [comment]
Its actually from the behaviours and depth...depending on whether the behaviour occurred below a certain depth and then the behaviour name (from the behaviour codes file - you can see in there which category each falls into)

**Comment by aptperson** [comment]
So it is an observed variable, not a measured variable.
You need to think if this can be calculated from the acc + depth on Wild data. Otherwise how can we use it?

**Comment by MoniqueLadds** [comment]
It can be, we have a wet/dry sensor so I know where they are

**Comment by aptperson** [comment]
Perfect! Thanks.
