### ISSUE TITLE
High frequency behaviours

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#4]
Can't reliably filter

**Comment by aptperson** [comment]
How do you want this handled? 
1. leave in the data as it's own behaviour to classify?
2. remove?
3. other.....

**Comment by MoniqueLadds** [comment]
Lets remove for now, there are only 38 cases

**Comment by MoniqueLadds** [comment]
feeding   foraging   grooming  high_freq      other    resting     thrash 
      1595        249        245         39       1338        876        303 
travelling 
      2844
