### ISSUE TITLE
Discrete time periods

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#5]
Related to other issues, I have code to do this, but lets get the dummies sorted first.

**Comment by aptperson** [comment]
In the word doc, it seems as if you want different time periods for different behaviours, how is this possible?
All splitting will need to be in the same length period, otherwise you would need to know a priori what the behaviour is, knowing a priori would render our research redundant.

**Comment by MoniqueLadds** [comment]
Oh whoops, that is not what I was implying. I want to try different time chunks to see what works

**Comment by aptperson** [comment]
Thought so, but just good to double check.
