### ISSUE TITLE
Misclassified behaviours

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#6]
Entirely possible. I will work on this now while I await responses to the other issues

**Comment by aptperson** [comment]
Which behaviours are you referring to? and which model are we using?
Models:
Model with the best perameters trained on
1. Training data
2. All of the data

Data
1. the in-sample miss-classification, 1 above
2. the validation 1 above
3 the in sample miss classification from 2 above?
3.1 from out of bag samples
3.2 re predicted from final model (this is preferred, if you want to track back to the actual behaviour videos)

**Comment by MoniqueLadds** [comment]
3.2 pretty pretty please!
