### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#7]
Discrete behaviours = the whole behaviour
Discrete time period behaviour = the XX Hz behaviour, where XX = 13,25,75 etc

**Comment by MoniqueLadds** [comment]
Yep, do you think this works? I wasn't exactly sure how to describe this.

**Comment by aptperson** [comment]
I don't like what I have above, I was seeking clarification on what we should call them.
Anything from biology land?
There should be a readme file in here some where, can you edit that once you have decided?

**Comment by MoniqueLadds** [comment]
It is difficult to explain but I would discuss it this way, it is easiest for when we write the paper.
So either;
- Discrete behaviour 
- Discrete time

**Comment by aptperson** [comment]
Thanks
