### ISSUE TITLE
Down/Up Sampling

### ISSUE THREAD

**Issue by aptperson** [aptperson/Seals-ML#8]
One small problem...we need to downsample much further than before...

feeding   1595
foraging   249
grooming  245
high_freq     39
 other    1338
resting    876
 thrash   303
travelling      2844

**Comment by aptperson** [comment]
To what level are you happy with the sampling?
Please check the literature and confirm here how you would like this done.

**Comment by MoniqueLadds** [comment]
Remove high_freq and sample to 250

**Comment by aptperson** [comment]
Thanks.
